### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by Xiariyouhu** [hiarindam/document-image-classification-TL-SG#6]
I'd like to use this algorithm to train some other ticket classification task. Could you offer the train code?

**Comment by saikat-roy** [comment]
Hi, thanks for your interest in our work. It has been a long time since we worked on this project and also since the training code was never meant for proper release, we unfortunately don't have access to the training code anymore and will be unable to provide you with it.

We would be happy to try and help you if you have questions on reimplementing the algorithm.
